#!/bin/bash

# R is for assigning a random number to it
R=0
DIRS=()

#copy motd into /etc/
cat /tmp/scenario-file-wrangler/motd/message.txt >> /etc/motd

for FILE in /home/*; do
    if [[ -d $FILE ]]; then
        DIRS+=( "$FILE" )
        echo $FILE
    fi
done
for studentDIR in "${DIRS[@]}"; do
    player=$(basename $studentDIR)
    cp /tmp/scenario-file-wrangler/motd/message.txt /$studentDIR/

    # Add an alias for all home directories
    cat /tmp/scenario-file-wrangler/cd_alias >> /$studentDIR/.bashrc

    # Copy the file hierarchy to each home directory
    cp -R /tmp/scenario-file-wrangler/files/* /$studentDIR/

    # Use EDURange variables for flags
    man_flag=$(edurange-get-var user $player manipulate)
    echo "SECRET FLAG: $man_flag" > /$studentDIR/codes/manipulate.txt

    perm_flag=$(edurange-get-var user $player permissions)
    echo "SECRET FLAG: $perm_flag" > /$studentDIR/codes/permissions.txt

    # Set file permissions
    chmod 600 /$studentDIR/codes/manipulate.txt
    chmod 600 /$studentDIR/codes/permissions.txt

    # Set python to run as root
    #chown root:root $studentDIR/manipulate/manflag.pyc
    #chmod 4775 $studentDIR/manipulate/manflag.pyc
    echo "$player ALL=(ALL) NOPASSWD: /usr/bin/python" >> /etc/sudoers
    #echo "$player ALL = (root) NOPASSWD: $studentDIR/permissions/perflag.pyc" >> /etc/sudoers

done
rm -r /tmp/scenario-file-wrangler
